# Generated by Django 4.2.19 on 2025-03-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('Patron', 'Patron'), ('Librarian', 'Librarian')], max_length=20, null=True),
        ),
    ]
