# Generated by Django 4.2.19 on 2025-03-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuereport',
            name='issue_type',
            field=models.CharField(choices=[('damaged_item', 'Damaged Item'), ('lost_item', 'Lost or Missing Item'), ('website_issue', 'Website Technical Issue'), ('equipment_malfunction', 'Equipment Malfunction'), ('cleanliness', 'Cleanliness Issue'), ('inventory_error', 'Inventory Discrepancy'), ('reservation_problem', 'Reservation Problem'), ('staff_assistance', 'Staff Assistance Needed'), ('other', 'Other Issue')], max_length=30),
        ),
        migrations.AlterField(
            model_name='issuereport',
            name='status',
            field=models.CharField(choices=[('Unreviewed', 'Unreviewed'), ('Reviewed', 'Reviewed'), ('In Progress', 'In Progress'), ('Accepted', 'Accepted'), ('Denied', 'Denied')], default='Unreviewed', max_length=20),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='status',
            field=models.CharField(choices=[('Unreviewed', 'Unreviewed'), ('Reviewed', 'Reviewed'), ('In Progress', 'In Progress'), ('Accepted', 'Accepted'), ('Denied', 'Denied')], default='Unreviewed', max_length=20),
        ),
    ]
