# Generated by Django 4.2.18 on 2025-04-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_alter_issuereport_issue_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuereport',
            name='status',
            field=models.CharField(choices=[('Unreviewed', 'Unreviewed'), ('Reviewed', 'Reviewed'), ('In Progress', 'In Progress'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Unreviewed', max_length=20),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='status',
            field=models.CharField(choices=[('Unreviewed', 'Unreviewed'), ('Reviewed', 'Reviewed'), ('In Progress', 'In Progress'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Unreviewed', max_length=20),
        ),
    ]
