# Generated by Django 4.2.20 on 2025-04-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_alter_issuereport_status_alter_itemrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuereport',
            name='status',
            field=models.CharField(choices=[('Unreviewed', 'Unreviewed'), ('Reviewed', 'Reviewed'), ('In Progress', 'In Progress'), ('Accepted', 'Accepted'), ('Denied', 'Denied')], default='Unreviewed', max_length=20),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='status',
            field=models.CharField(choices=[('Unreviewed', 'Unreviewed'), ('Reviewed', 'Reviewed'), ('In Progress', 'In Progress'), ('Accepted', 'Accepted'), ('Denied', 'Denied')], default='Unreviewed', max_length=20),
        ),
    ]
