# Generated by Django 4.2.20 on 2025-04-10 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_alter_issuereport_status_alter_itemrequest_status'),
        ('form', '0005_itemrequest_librarian'),
    ]

    operations = [
    ]
