# Generated by Django 4.2.18 on 2025-04-11 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_itemrequest_librarian'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequest',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
