# Generated by Django 4.2.20 on 2025-04-11 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_itemrequest_returned'),
        ('form', '0006_merge_20250410_0831'),
    ]

    operations = [
    ]
