# Generated by Django 4.2.19 on 2025-04-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_itemrequest_returned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequest',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
