# Generated by Django 4.2.19 on 2025-04-26 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0009_itemrequest_is_seen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemrequest',
            old_name='is_seen',
            new_name='is_seen_by_patron',
        ),
    ]
