# Generated by Django 4.2.19 on 2025-04-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0010_rename_is_seen_itemrequest_is_seen_by_patron'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequest',
            name='is_seen_by_librarian',
            field=models.BooleanField(default=False),
        ),
    ]
