# Generated by Django 4.2.18 on 2025-02-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('condition', models.CharField(choices=[('brand_new', 'Brand New'), ('gently_used', 'Gently Used'), ('good', 'Good Condition'), ('worn', 'Worn Condition'), ('poor', 'Poor Condition')], max_length=20)),
            ],
        ),
    ]
