# Generated by Django 4.2.18 on 2025-02-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.CharField(choices=[('brand_new', 'Brand New'), ('gently_used', 'Gently Used'), ('good', 'Good Condition'), ('worn', 'Worn Condition')], max_length=20),
        ),
    ]
