# Generated by Django 4.2.18 on 2025-03-14 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_borrowrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowrequest',
            name='status',
        ),
        migrations.AddField(
            model_name='item',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
