# Generated by Django 4.2.18 on 2025-03-24 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_item_photo'),
        ('inventory', '0005_remove_item_is_available_borrowrequest_status'),
    ]

    operations = [
    ]
