# Generated by Django 4.2.19 on 2025-03-27 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_collection'),
        ('inventory', '0007_alter_item_title'),
    ]

    operations = [
    ]
