# Generated by Django 4.2.20 on 2025-04-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_merge_0004_collection_0007_alter_item_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
