# Generated by Django 4.2.19 on 2025-03-31 09:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0008_merge_0004_collection_0007_alter_item_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[
                    ("cookware", "Cookware"),
                    ("spices", "Spices"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="published_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
