# Generated by Django 4.2.18 on 2025-04-02 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0008_merge_0004_collection_0007_alter_item_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='uploader',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_items', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
