# Generated by Django 4.2.19 on 2025-03-31 23:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0009_item_category_item_published_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="location",
            field=models.CharField(
                choices=[
                    ("home_library", "Home Library"),
                    ("work_library", "Work Library"),
                    ("other", "Other"),
                ],
                default="home_library",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="primary_identifier",
            field=models.CharField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="ratings_and_comments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="status",
            field=models.CharField(
                choices=[
                    ("checked_in", "Checked In"),
                    ("in_circulation", "In Circulation"),
                    ("being_repaired", "Being Repaired"),
                    ("lost", "Lost"),
                ],
                default="checked_in",
                max_length=20,
            ),
        ),
    ]
