# Generated by Django 4.2.19 on 2025-04-01 00:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0010_item_location_item_primary_identifier_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="ratings_and_comments",
        ),
    ]
