# Generated by Django 4.2.18 on 2025-04-06 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0011_borrowrequest_librarian'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='librarian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_borrows', to=settings.AUTH_USER_MODEL),
        ),
    ]
