# Generated by Django 4.2.20 on 2025-04-08 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_item_is_private'),
        ('inventory', '0012_borrowrequest_due_date_alter_borrowrequest_librarian'),
    ]

    operations = [
    ]
