# Generated by Django 4.2.18 on 2025-04-11 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_borrowrequest_due_date_alter_borrowrequest_librarian'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
