# Generated by Django 4.2.19 on 2025-04-11 04:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
#         ("inventory", "0011_remove_item_ratings_and_comments"),
        ("inventory", "0013_borrowrequest_returned"),
    ]

    operations = []
