# Generated by Django 4.2.20 on 2025-04-09 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_merge_20250408_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_private',
        ),
    ]
