# Generated by Django 4.2.20 on 2025-04-11 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_remove_item_ratings_and_comments"),
        ("inventory", "0014_merge_20250411_0037"),
    ]

    operations = []
