# Generated by Django 4.2.20 on 2025-04-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0015_merge_20250411_0302"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="location",
            field=models.CharField(default="Charlottesville, VA", max_length=50),
        ),
        migrations.AlterField(
            model_name="item",
            name="status",
            field=models.CharField(
                choices=[
                    ("checked in", "Checked In"),
                    ("in circulation", "In Circulation"),
                    ("being repaired", "Being Repaired"),
                    ("lost", "Lost"),
                ],
                default="checked_in",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
