# Generated by Django 4.2.20 on 2025-04-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0016_alter_item_location_alter_item_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="published_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="status",
            field=models.CharField(
                choices=[
                    ("checked in", "Checked In"),
                    ("in circulation", "In Circulation"),
                    ("being repaired", "Being Repaired"),
                    ("lost", "Lost"),
                ],
                default="Checked In",
                max_length=20,
            ),
        ),
    ]
