# Generated by Django 4.2.20 on 2025-04-11 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_remove_item_is_private'),
        ('inventory', '0018_alter_item_title_rating_comment'),
    ]

    operations = [
    ]
