# Generated by Django 4.2.18 on 2025-04-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_merge_20250411_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
