# Generated by Django 4.2.19 on 2025-04-21 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_borrowrequest_returned_at'),
        ('inventory', '0020_collectionaccessrequest'),
    ]

    operations = [
    ]
