# Generated by Django 4.2.19 on 2025-04-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_merge_20250421_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collectionaccessrequest',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='collection',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='collections', to='inventory.item'),
        ),
    ]
