# Generated by Django 4.2.19 on 2025-04-26 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_borrowrequest_is_seen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowrequest',
            old_name='is_seen',
            new_name='is_seen_by_patron',
        ),
        migrations.RenameField(
            model_name='collectionaccessrequest',
            old_name='is_seen',
            new_name='is_seen_by_patron',
        ),
    ]
