# Generated by Django 4.2.19 on 2025-04-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_rename_is_seen_borrowrequest_is_seen_by_patron_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='is_seen_by_librarian',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collectionaccessrequest',
            name='is_seen_by_librarian',
            field=models.BooleanField(default=False),
        ),
    ]
