# Generated by Django 4.2.20 on 2025-04-11 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_moderation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermoderation',
            options={'ordering': ['-created_at'], 'verbose_name': 'User Moderation Action', 'verbose_name_plural': 'User Moderation Actions'},
        ),
    ]
