# Generated by Django 4.2.20 on 2025-04-11 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_moderation', '0002_alter_usermoderation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermoderation',
            name='removal_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usermoderation',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermoderation',
            name='removed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderations_removed', to=settings.AUTH_USER_MODEL),
        ),
    ]
